version: "3.7"

services:
  mysql:
    container_name: 'db'
    image: mysql
    ports:
      - '3306:3306'
    environment:
      MYSQL_ROOT_PASSWORD: 'passWord'
      MYSQL_PASSWORD: 'passWord'
      MYSQL_DATABASE: 'agenda'
      MYSQL_USER: 'fran'
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      retries: 10
      interval: 5s

  node:
    container_name: 'api'
    build:
      context: .
      dockerfile: Dockerfile-node
    ports:
      - '3000:3000'
    depends_on:
      mysql:
        condition: service_healthy
